"""Forced alignment of the canonical lyric sheet to the vocal stem, section by section (timing pass 2, Ra 9/25:
"the lyrics aren't quite in sync everywhere").

Pass 1 (align_canon.py) borrowed whisper's word times and interpolated the words whisper misheard, which is worst
exactly in the fast bars. Here the text is fixed and only timing is searched: torchaudio's MMS_FA wav2vec2 model
gives per-frame character probabilities and CTC forced alignment finds the best path through the known lyric, with
a <star> token between lines to soak up ad-libs and echoes (descends from deep_time_mv/align_fa.py).

Whole-song alignment derails on rap (IGNITION's lesson), so each section is aligned inside its own window, with the
window edges taken from the pass-1 line starts. Onsets are then snapped to the vocal-stem onset table within 60 ms.

Writes src/lyrics.js in the same shape as before (LYR = [[t, word, lineIdx]], LINES) and prints every word that
moved more than 0.2 s so the chapters' hand overrides can be re-checked.
"""
import json, re
import numpy as np, soundfile as sf, torch, torchaudio

STEM = "analysis/stems/htdemucs/track/vocals.wav"
canon = [l.strip() for l in open("analysis/lyrics_canon.txt") if l.strip()]
old = json.loads(open("src/lyrics.js").read().split("const LYR = ")[1].split(";\n")[0])
old_lines = json.loads(open("src/lyrics.js").read().split("const LINES = ")[1].split(";\n")[0])
ONS = np.array(json.load(open("analysis/onsets.json")))

# sections as (first line index, last line index, window start, window end)
def L(prefix, after=0):
    for i, (t, text) in enumerate(old_lines):
        if t >= after - .01 and text.lower().startswith(prefix.lower()): return i
    raise KeyError(prefix)
SECTIONS = [
    (0, L("And maybe you can relate") - 1, 0.0, 30.0),
    (L("And maybe you can relate"), L("When I said", 47) - 1, 29.8, 47.75),
    (L("When I said", 47), L("They call me") - 1, 47.4, 62.7),
    (L("They call me"), L("And maybe you can’t") - 1, 62.0, 77.3),
    (L("And maybe you can’t"), L("When I said", 95) - 1, 76.8, 95.0),
    (L("When I said", 95), L("Praise you") - 1, 94.8, 112.0),
    (L("Praise you"), L("When I said", 140) - 1, 113.4, 137.5),
    (L("When I said", 140), L("When I said", 155) - 1, 140.2, 155.8),
    (L("When I said", 155), L("“So…it just") - 1, 155.5, 179.3),
    (L("“So…it just"), len(canon) - 1, 179.3, 199.0),
]

SPECIAL = {"404": ["four", "oh", "four"], "5am": ["five", "a", "m"], "mov.": ["m", "o", "v"], "mov": ["m", "o", "v"],
           "ctrl-alt-amen-break": ["control", "alt", "amen", "break"], "love.exe-me,": ["love", "exe", "me"],
           "onnnnn…": ["on"], "….come": ["come"]}
def romanize(w):
    k = w.lower().replace("’", "'")
    if k in SPECIAL: return SPECIAL[k]
    return [p for p in re.sub(r"[^a-z' ]", " ", k.replace("-", " ")).split() if p] or ["a"]

bundle = torchaudio.pipelines.MMS_FA
model, tok, aligner = bundle.get_model(with_star=True), bundle.get_tokenizer(), bundle.get_aligner()
data, sr = sf.read(STEM, dtype="float32")
mono = data.mean(axis=1) if data.ndim > 1 else data
wave = torchaudio.functional.resample(torch.from_numpy(mono)[None], sr, bundle.sample_rate)
SR16, HOP = bundle.sample_rate, 320

times = {}
for (l0, l1, a, b) in SECTIONS:
    seg = wave[:, int(a * SR16):int(b * SR16)]
    with torch.inference_mode(): em, _ = model(seg)
    pieces, owners = ["*"], [None]
    for li in range(l0, l1 + 1):
        for wi, w in enumerate(canon[li].split()):
            for p in romanize(w): pieces.append(p); owners.append((li, wi))
        pieces.append("*"); owners.append(None)
    spans = aligner(em[0], tok(pieces))
    for ow, sp in zip(owners, spans):
        if ow is None or not sp: continue
        s = a + sp[0].start * HOP / SR16
        if ow not in times: times[ow] = s

LYR, moved = [], []
flat_old = {}
k = 0
for li, text in enumerate(canon):
    for wi, w in enumerate(text.split()):
        t = times.get((li, wi))
        t_old = old[k][0]; k += 1
        if t is None: t = t_old
        j = np.argmin(np.abs(ONS - t))
        if abs(ONS[j] - t) <= .06: t = float(ONS[j])
        LYR.append([round(t, 3), w, li])
        if abs(t - t_old) > .2: moved.append((w, li, t_old, t))
for i in range(1, len(LYR)): LYR[i][0] = max(LYR[i][0], LYR[i - 1][0] + .01)
LINES = []
for li, text in enumerate(canon):
    LINES.append([next(x[0] for x in LYR if x[2] == li), text])
open("src/lyrics.js", "w").write("// GENERATED by analysis/align_fa.py: canonical lyric words, CTC forced alignment per section (MMS_FA) snapped\n"
  "// to vocal-stem onsets within 60 ms. LYR = [[t, word, lineIdx]], LINES = [[t0, line]]. Look up with wt()/wh() (kit.js).\n"
  "const LYR = " + json.dumps(LYR, ensure_ascii=False) + ";\nconst LINES = " + json.dumps(LINES, ensure_ascii=False, indent=0) + ";\n")
json.dump([[w, li, a, b] for w, li, a, b in moved], open("analysis/fa_moved.json", "w"), indent=0)
print(f"{len(LYR)} words; {len(moved)} moved > 0.2 s")
for w, li, a, b in moved: print(f"  {a:7.2f} -> {b:7.2f} ({b - a:+5.2f})  {w}   | {canon[li][:50]}")
