"""Canonical lyric sheet → per-word times, by aligning its words to whisper's (snapped) words with difflib.
Matched words take whisper's snapped onset; runs of unmatched words are spread across the gap between their matched
neighbours, weighted by length. Writes src/lyrics.js: LYR = [[t, word, lineIdx], ...] and LINES = [[t0, text], ...].
Whisper mishears the fast bars ("sycophantic" → "sick of panic"), so the canonical text is what chapters look up."""
import json, re, difflib
canon = [l.strip() for l in open("analysis/lyrics_canon.txt") if l.strip()]
wh = json.loads(open("src/lyrics.js").read().split("const LYR = ")[1].rstrip(";\n")) if "lineIdx" not in open("src/lyrics.js").read() else None
if wh is None: wh = json.load(open("analysis/lyr_whisper.json"))
json.dump(wh, open("analysis/lyr_whisper.json", "w"))
norm = lambda s: re.sub(r"[^a-z0-9]", "", s.lower().replace("’", "'"))
cw = [(w, i) for i, l in enumerate(canon) for w in l.split()]
a = [norm(w) for w, _ in cw]; b = [norm(x[1]) for x in wh]
sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
t = [None] * len(cw)
for blk in sm.get_matching_blocks():
    for k in range(blk.size): t[blk.a + k] = wh[blk.b + k][0]
# interpolate gaps
i = 0
while i < len(t):
    if t[i] is None:
        j = i
        while j < len(t) and t[j] is None: j += 1
        lo = t[i - 1] if i > 0 else 0.0
        hi = t[j] if j < len(t) else lo + 0.3 * (j - i)
        L = [len(a[k]) + 1 for k in range(i, j)]; tot = sum(L) + 1; acc = 0
        for k in range(i, j): acc += L[k - i]; t[k] = lo + (hi - lo) * acc / tot
        i = j
    else: i += 1
# enforce monotonic
for k in range(1, len(t)): t[k] = max(t[k], t[k - 1] + 0.01)
LYR = [[round(t[k], 3), cw[k][0], cw[k][1]] for k in range(len(cw))]
LINES = []
for li, text in enumerate(canon):
    ks = [k for k in range(len(cw)) if cw[k][1] == li]; LINES.append([round(t[ks[0]], 3), text])
matched = sum(1 for blk in sm.get_matching_blocks() for _ in range(blk.size))
open("src/lyrics.js", "w").write("// GENERATED by analysis/align_canon.py (lineIdx): canonical lyric words timed from whisper + vocal onsets.\n"
  "// LYR = [[t, word, lineIdx]], LINES = [[t0, line]]. Look words up with wt('word', after) (kit.js).\n"
  "const LYR = " + json.dumps(LYR, ensure_ascii=False) + ";\nconst LINES = " + json.dumps(LINES, ensure_ascii=False, indent=0) + ";\n")
print(f"{len(cw)} canonical words, {matched} matched to whisper")
for l in LINES: print(f"{l[0]:7.2f}  {l[1]}")
