"""Timing pass 2: merge whisper-snapped times (pass 1) with CTC forced alignment (align_fa.py), word by word.

Spot checks against the vocal-stem energy (syllable dips) on 9/25 showed:
- mid-line, pass 1 lands on the attack; forced alignment runs ~0.25 s late (CTC spikes sit inside the phone, and
  on rap the model smears);
- pass 1 is wrong in two known ways: whisper stretches the FIRST word of each segment back toward the previous
  silence (e.g. "We" 16.30 for a word sung ~16.9), and every word whisper misheard was only interpolated
  ("sycophantic" 63.90, really 63.30; "hyperobject" 77.05, really ~76.3; "logged on" inside the instrumental).
So: keep pass 1 where whisper really heard the word and it isn't line-initial; otherwise use the forced-aligned time
minus the measured lag, snapped to a vocal onset within 0.1 s. Prints every change > 0.12 s.
"""
import json, re, difflib
import numpy as np

canon = [l.strip() for l in open("analysis/lyrics_canon.txt") if l.strip()]
P1 = json.loads(open("analysis/lyrics_pass1.js").read().split("const LYR = ")[1].split(";\n")[0])
FA = json.loads(open("analysis/lyrics_fa.js").read().split("const LYR = ")[1].split(";\n")[0])
WH = json.load(open("analysis/lyr_whisper.json"))
ONS = np.array(json.load(open("analysis/onsets.json")))
norm = lambda s: re.sub(r"[^a-z0-9]", "", s.lower().replace("’", "'"))

# which canonical words did whisper actually hear (difflib match, same as align_canon.py)?
a = [norm(w) for _, w, _ in P1]; b = [norm(x[1]) for x in WH]
heard = set()
for blk in difflib.SequenceMatcher(None, a, b, autojunk=False).get_matching_blocks():
    heard.update(range(blk.a, blk.a + blk.size))
first = {i for i in range(len(P1)) if i == 0 or P1[i][2] != P1[i - 1][2]}

# CTC lag, measured on words both methods agree are the same syllable (heard, mid-line, within 0.5 s)
d = [FA[i][0] - P1[i][0] for i in range(len(P1)) if i in heard and i not in first and abs(FA[i][0] - P1[i][0]) < .5]
LAG = float(np.median(d))
print(f"CTC lag (median over {len(d)} agreeing words): {LAG:+.3f} s")

def snap(t, win=.1):
    j = np.argmin(np.abs(ONS - t)); return float(ONS[j]) if abs(ONS[j] - t) <= win else t

# Hand rulings, checked against the vocal-stem energy (9/25):
# - "And maybe you can't relate": the "-ject" of hyperobject is held to 78.3, silence, then the line at ~78.6;
#   whisper put "And maybe" at 77.14/77.63 (inside the held vowel). Use the aligner for the whole line.
# - the second "on and on again": sung at 173.10 (whisper heard it); the aligner skipped to the unlisted third
#   repeat at ~177. Keep pass 1 for that line.
FA_LINES = {li for li, text in enumerate(canon) if text.startswith("And maybe you can’t relate")}
oa = [li for li, text in enumerate(canon) if text == "on and on again"]
P1_LINES = {oa[-1]}
# - hook 3 "you're still talkin to a ghost at 5am": an ad-lib the sheet doesn't have ("you're so f—ing special",
#   148.84–149.6) sits right before it, and the aligner gave the ad-lib's "you're" to this line. Whisper's line
#   ("You're talking to a ghost at 5am", 149.70) is right: pass 1 for the line, with "you're" on 149.70's onset.
h3 = [li for li, text in enumerate(canon) if text.startswith("you’re still talkin")][0]
P1_LINES.add(h3)
PIN = {(h3, 0): 149.70}
out, changed = [], []
for i, (t1, w, li) in enumerate(P1):
    wi = sum(1 for x in P1[:i] if x[2] == li)
    if (li, wi) in PIN: t = snap(PIN[(li, wi)], .08); why = "pinned"
    elif li in P1_LINES: t = t1; why = "p1 (ruling)"
    elif li in FA_LINES: t = snap(FA[i][0] - LAG); why = "fa-lag (ruling)"
    elif i in heard and i not in first: t = t1; why = "p1"
    else: t = snap(FA[i][0] - LAG); why = "fa-lag" + (" (line start)" if i in first else " (misheard)")
    out.append([round(t, 3), w, li])
    if abs(t - t1) > .12: changed.append((t1, t, w, li, why))
for i in range(1, len(out)): out[i][0] = max(out[i][0], out[i - 1][0] + .01)
LINES = [[next(x[0] for x in out if x[2] == li), text] for li, text in enumerate(canon)]
open("src/lyrics.js", "w").write("// GENERATED by analysis/merge_timing.py (timing pass 2): whisper-snapped times where whisper heard the word\n"
  "// mid-line, else CTC forced alignment minus its measured lag. LYR = [[t, word, lineIdx]], LINES = [[t0, line]].\n"
  "const LYR = " + json.dumps(out, ensure_ascii=False) + ";\nconst LINES = " + json.dumps(LINES, ensure_ascii=False, indent=0) + ";\n")
json.dump(changed, open("analysis/timing_pass2_changes.json", "w"), indent=0)
print(f"{len(changed)} words moved > 0.12 s")
for t1, t, w, li, why in changed: print(f"  {t1:7.2f} -> {t:7.2f} ({t - t1:+5.2f})  {w:22s} {why}")
