"""Snap whisper word starts to vocal-stem onsets (±0.15 s) → src/lyrics.js (LYR = [[t, word], ...]) + analysis/onsets.json.
Whisper's word times drift by up to ~0.2 s on fast rap; the stem onsets are where the consonants actually hit."""
import json, numpy as np, librosa
y, sr = librosa.load("analysis/stems/htdemucs/track/vocals.wav", sr=22050, mono=True)
on = librosa.onset.onset_detect(y=y, sr=sr, hop_length=128, units="time", backtrack=False, delta=0.05)
words = json.load(open("analysis/words.json"))
out, moved = [], []
for w in words:
    s = w["s"]; j = np.argmin(np.abs(on - s)); d = on[j] - s
    t = float(on[j]) if abs(d) <= 0.15 else s
    out.append([round(t, 3), w["w"], round(w["e"], 3)]); moved.append(abs(t - s))
json.dump([round(float(x), 3) for x in on], open("analysis/onsets.json", "w"))
open("src/lyrics.js", "w").write("// GENERATED by analysis/snap.py: whisper words snapped to vocal-stem onsets. [start, word, end]. Hand-fix in LYRFIX (kit.js).\nconst LYR = " + json.dumps(out) + ";\n")
print(len(out), "words; median snap %.3f s; %d onsets" % (np.median(moved), len(on)))
